import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NEXT_APPWRITE_KEY: z.string(),
  },
  client: {
    NEXT_PUBLIC_APPWRITE_ENDPOINT: z.string().url(),
    NEXT_PUBLIC_APPWRITE_PROJECT: z.string(),
    NEXT_PUBLIC_APPWRITE_DATABASE: z.string(),
    NEXT_PUBLIC_APPWRITE_USERS_COLLECTION: z.string(),
    NEXT_PUBLIC_APPWRITE_FILES_COLLECTION: z.string(),
    NEXT_PUBLIC_APPWRITE_BUCKET: z.string(),
  },
  runtimeEnv: {
    NEXT_APPWRITE_KEY: process.env.NEXT_APPWRITE_KEY,
    NEXT_PUBLIC_APPWRITE_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT,
    NEXT_PUBLIC_APPWRITE_PROJECT: process.env.NEXT_PUBLIC_APPWRITE_PROJECT,
    NEXT_PUBLIC_APPWRITE_DATABASE: process.env.NEXT_PUBLIC_APPWRITE_DATABASE,
    NEXT_PUBLIC_APPWRITE_USERS_COLLECTION:
      process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION,
    NEXT_PUBLIC_APPWRITE_FILES_COLLECTION:
      process.env.NEXT_PUBLIC_APPWRITE_FILES_COLLECTION,
    NEXT_PUBLIC_APPWRITE_BUCKET: process.env.NEXT_PUBLIC_APPWRITE_BUCKET,
  },
});
